const noop = () => {};
export const a = noop;
export const b = noop;
export const c = noop;
export const d = noop;
export const i = noop;
export const k = noop;
export const l = noop;
export const o = noop;
export const p = noop;
export const r = noop;
export const u = noop;
export const v = noop;